---
- name: Install tmuxp
  pip:
    name: tmuxp
    state: present
  when: not (tmux_tmuxp_executable or tmux_tmuxp_virtualenv)

- name: Install tmuxp with specified Python version
  pip:
    name: tmuxp
    executable: "{{ tmux_tmuxp_executable }}"
    state: present
  when: tmux_tmuxp_executable and not tmux_tmuxp_virtualenv

- name: Install tmuxp into a virtual environment
  pip:
    name: tmuxp
    virtualenv: "{{ tmux_tmuxp_virtualenv }}"
    state: present
  when: tmux_tmuxp_virtualenv and not tmux_tmuxp_virtualenv_command

- name: Install tmuxp into a virtual environment with specified venv command
  pip:
    name: tmuxp
    virtualenv: "{{ tmux_tmuxp_virtualenv }}"
    virtualenv_command: "{{ tmux_tmuxp_virtualenv_command }}"
    state: present
  when: tmux_tmuxp_virtualenv and tmux_tmuxp_virtualenv_command
